on: push
jobs:
  build-runner:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

testing:
    needs: build-runner
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1
      - name: install dependencies
        run: python -m pip install --upgrade pip && python -m pip install -r requirements.txt
      - name: run Pylama
        run: pylama
      - name: run Bandit
        run: bandit .
      - name: run performance tests
        run: python -m locust --users 1 --spawn-rate 1 --run-time 1s --headless
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: performance-test-report
          path: locust_html_report.html
          retention-days: 5