[package]
name = "funding-service-design-performance-tests"
version = "0.0.1"
description = "The funding service design performance tests for the DLUHC."
authors = ["Evoco Digital Services"]
license = "MIT License"

[tool.black]
line-length = 79
experimental-string-processing = 1
