name: Funding Service Design Performance Test Pipeline
on: push
jobs:
  build-runner:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

  testing:
      needs: build-runner
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.10.1
        - name: install dependencies
          run: python -m pip install --upgrade pip && python -m pip install -r requirements.txt
        - name: run Pylama
          run:  pylama --format json --report pylama_report.json
        - name: Upload Pylama Report
          uses: actions/upload-artifact@v2
          with:
            name: pylama_report.json
            path: pylama_report.json
            retention-days: 5
        - name: run Bandit
          run: bandit . -f json -o bandit_security.json
        - name: Upload Pylama Report
          uses: actions/upload-artifact@v2
          with:
            name: bandit_security.json
            path: bandit_security.json
            retention-days: 5
        - name: run performance tests
          run: python -m locust --users 3 --spawn-rate 1 --run-time 1s --headless
          continue-on-error: true
        - name: Upload Pylama Report
          uses: actions/upload-artifact@v2
          with:
            name: locust_html_report.html
            path: locust_html_report.html
            retention-days: 5