name: Funding Service Design Performance Test Pipeline
on: push
jobs:
  build-runner:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.3
        with:
          ref: ${{ github.event.inputs.branch }}

  testing:
      needs: build-runner
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v3.5.3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.10.x
        - name: Install dependencies
          run: python -m pip install --upgrade pip && python -m pip install -r requirements.txt
        - name: Run Bandit
          run: bandit . -f json -o bandit_security.json
        - name: Upload Pylama Report
          uses: actions/upload-artifact@v3
          with:
            name: bandit_security.json
            path: bandit_security.json
            retention-days: 5
        - name: Run performance tests
          run: python -m locust --users 3 --spawn-rate 1 --run-time 15s --headless
          continue-on-error: true
        - name: Upload Pylama Report
          uses: actions/upload-artifact@v3
          with:
            name: locust_html_report.html
            path: locust_html_report.html
            retention-days: 5
